services:
  postgres:
    image: postgres
    container_name: files-manager-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:alpine
    container_name: files-manager-redis
    restart: always
    ports:
      - 6379:6379

volumes:
  data:
    driver: local
